# Macro file for example LXe
# Written by Keavan Andreassen
#
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode)
#/run/numberOfWorkers 16
#
# Initialize kernel
/run/initialize
#
#/control/verbose 2
#/run/verbose 2
#/event/verbose 0
#/tracking/verbose 1
#
# electron 2.5 MeV to the direction (0.,0.,1.)
#
/gun/particle e-
/gun/energy 2.5 MeV
#
/run/printProgress 20
/run/beamOn 1000
